export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const SET = "SET"
export const ADMIN = "ADMIN"
export const STATE = "STATE"
export const MAIN = "MAIN"
export const CHECK = "CHECK"
